version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
